name: iron_mind
description: "IRON MIND - Suivi de roadmap personnelle de performance sur 4 mois."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^13.2.4

  # Gestion d'état
  flutter_riverpod: ^2.5.1

  # Stockage local (Hive — sans génération de code)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4

  # Polices & Icons
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1

  # Animations
  flutter_animate: ^4.5.0
  flutter_screenutil: ^5.9.0

  # Graphiques
  fl_chart: ^0.68.0

  # Utilitaires
  intl: ^0.19.0
  logger: ^2.4.0
  shared_preferences: ^2.2.3
  uuid: ^4.4.2
  collection: ^1.18.0

  cupertino_icons: ^1.0.8

  # Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  permission_handler: ^11.3.1

  # Gamification
  audioplayers: ^6.4.0
  haptic_feedback: ^0.5.1+2

  # Animations
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/sounds/
    - assets/sounds/

  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-VariableFont_wght.ttf
#    - family: JetBrainsMono
#      fonts:
#        - asset: assets/fonts/JetBrainsMono-Regular.ttf
#        - asset: assets/fonts/JetBrainsMono-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/JetBrainsMono-Bold.ttf
#          weight: 700
